# data paths
save_dataloaders: False
save_dataset: False
checkpoint_dir: "train/saved/"

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, rating, timestamp]

# data filtering for interactions
# val_interval:
#     rating: "[3,inf)"
# unused_col: 
#     inter: [rating]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
valid_metric: NDCG@10
topk: [1, 3, 5, 10, 20]
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
train_neg_sample_args: ~

eval_step: 5

# model
embedding_size: 64